[valuestore]
Master = true
NetFilter = ["10.0.0.0/8"]
Port = 8443
MsgRingPort = 8001
CmdCtrlPort = 4444
CertFile = "/etc/oort/server.crt"
KeyFile = "/etc/oort/server.key"
RingDir = "/etc/oort/ring/value"
WeightAssignment = "self"

[groupstore]
Master = true
NetFilter = ["10.0.0.0/8"]
Port = 8444
MsgRingPort = 8002
CmdCtrlPort = 4445
CertFile = "/etc/oort/server.crt"
KeyFile = "/etc/oort/server.key"
RingDir = "/etc/oort/ring/group"
WeightAssignment = "self"

#[llamasherpaderpa2000]
#Master = true
#Slaves = []
#NetFilter = ["192.168.1.1/27"]
#Port = 8445
#CmdCtrlPort = 4445
